=== lups-ufpel/PampaSim/memory/src/main/resources/org/pampasim/resources/memory/MemoryManagement.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://pampasim.org/memory"
           xmlns="http://pampasim.org/memory"
           elementFormDefault="qualified">
    <xs:element name="MMU">
        <xs:complexType>
            <xs:all>
                <xs:element name="pageSizeKb" type="xs:positiveInteger" default="1"/>
                <xs:element name="maxPagesPerProcess" type="xs:positiveInteger" default="24"/>
                <xs:element name="framesInRam" type="xs:positiveInteger" default="32"/>
                <xs:element name="framesInSwap" type="xs:positiveInteger" default="64"/>
                <xs:element name="swapOperationLength" type="xs:unsignedInt" default="3"/>
                <xs:element name="workingSetWindow" type="xs:unsignedInt" default="10"/>
                <!-- Name type is a stand-in for a proper java FQCN type -->
                <xs:element name="pageSubstitutionAlgorithm" type="xs:Name" default="FIFO"/>
                <xs:element name="globalPageSubstitution" type="xs:boolean" default="true"/>
                <xs:element name="anticipatedPageLoading" type="xs:boolean" default="true"/>
                <xs:element name="prePagingRange" type="xs:unsignedInt" default="5"/>
                <xs:element name="variablePageAllocation" type="xs:boolean" default="false"/>
                <xs:element name="variablePageAllocationThresholds" default="0.25 0.75">
                    <xs:simpleType>
                        <xs:list itemType="xs:double"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="tlbEnabled" type="xs:boolean" default="false"/>
                <xs:element name="tlbEntries" type="xs:unsignedInt" default="16"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== lups-ufpel/PampaSim/memory/src/main/resources/org/pampasim/resources/memory/memoryModuleTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>

<MMU
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://pampasim.org/memory"
        xsi:schemaLocation="http://pampasim.org/memory memoryManagement.xsd">
    <pageSizeKb>1</pageSizeKb>
    <maxPagesPerProcess>24</maxPagesPerProcess>
    <framesInRam>32</framesInRam>
    <framesInSwap>64</framesInSwap>
    <swapOperationLength>3</swapOperationLength>
    <workingSetWindow>10</workingSetWindow>
    <!-- Name type is a stand-in for a proper java FQCN type -->
    <pageSubstitutionAlgorithm>FIFO</pageSubstitutionAlgorithm>
    <globalPageSubstitution>true</globalPageSubstitution>
    <anticipatedPageLoading>true</anticipatedPageLoading>
    <prePagingRange>5</prePagingRange>
    <variablePageAllocation>false</variablePageAllocation>
    <variablePageAllocationThresholds>0.25 0.75</variablePageAllocationThresholds>
    <tlbEnabled>false</tlbEnabled>
    <tlbEntries>16</tlbEntries>
</MMU>
