=== lups-ufpel/PampaSim/schemas/simulationDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="simulationDescription">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="events" type="eventDeclaration"/>
                <xs:element name="entity" type="entityDeclaration" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="eventDeclaration">
        <xs:sequence>
            <xs:element name="eventGroup" type="eventGroup" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="eventGroup">
        <xs:sequence>
            <xs:element name="payloads">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="fullyQualifiedClassName" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="event" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="entityDeclaration">
        <xs:sequence>
            <xs:element name="handler" type="handlerDeclaration" maxOccurs="unbounded"/>
            <xs:element name="produces" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="event" type="eventIdentifier"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="handlerDeclaration">
        <xs:sequence>
            <xs:element name="event" type="eventIdentifier"/>
            <xs:element name="do" type="xs:string"/>
            <xs:element name="chains" minOccurs="0" type="chainsADT">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="chainsADT">
        <xs:choice>
            <xs:element name="event" type="eventIdentifier"/>
            <xs:element name="or">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="alt" type="chainsADT" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="eventIdentifier">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="group" type="xs:string"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== lups-ufpel/PampaSim/declarations/processManagement.xml
<?xml version="1.0" encoding="UTF-8"?>

<simulationDescription
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schemas/simulationDescription.xsd">
    <events>
        <eventGroup name="External">
            <payloads>
                <class>
                    <fullyQualifiedClassName>org.pampasim.resources.Process$CreationData</fullyQualifiedClassName>
                    <schema>../schemas/events/processCreationData</schema>
                </class>
            </payloads>
            <event>Arrival</event>
        </eventGroup>
        <eventGroup name="Process">
            <payloads>
                <class>
                    <fullyQualifiedClassName>org.pampasim.resources.Process</fullyQualifiedClassName>
                </class>
            </payloads>
            <event>Allocate</event>
            <event>Ready</event>
            <event>Schedule</event>
            <event>Dispatch</event>
            <event>Run</event>
            <event>Load</event>
            <event>IoOperation</event>
            <event>Preemption</event>
            <event>RunPaused</event>
            <event>End</event>
            <event>Kill</event>
        </eventGroup>
    </events>
    <entity name="ProcessManager">
        <handler>
            <event>
                <name>Arrival</name>
                <group>External</group>
            </event>
            <do>create process</do>
            <chains>
                <event>
                    <name>Allocate</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>Ready</name>
                <group>Process</group>
            </event>
            <do>schedule for execution</do>
            <chains>
                <event>
                    <name>Schedule</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>RunPaused</name>
                <group>Process</group>
            </event>
            <do>schedule for execution or end process</do>
            <chains>
                <or>
                    <alt>
                        <event>
                            <name>Schedule</name>
                            <group>Process</group>
                        </event>
                    </alt>
                    <alt>
                        <event>
                            <name>End</name>
                            <group>Process</group>
                        </event>
                    </alt>
                </or>
            </chains>
        </handler>
    </entity>
    <entity name="Scheduler">
        <handler>
            <event>
                <name>Schedule</name>
                <group>Process</group>
            </event>
            <do>bring process to memory</do>
            <chains>
                <event>
                    <name>Dispatch</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <produces>
            <event>
                <name>Preemption</name>
                <group>Process</group>
            </event>
        </produces>
    </entity>
    <entity name="Processor">
        <handler>
            <event>
                <name>Preemption</name>
                <group>Process</group>
            </event>
            <do>suspend and evict current process</do>
            <chains>
                <event>
                    <name>RunPaused</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>Dispatch</name>
                <group>Process</group>
            </event>
            <do>load pages for current execution tick</do>
            <chains>
                <event>
                    <name>Run</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
    </entity>
    <entity name="Memory">
        <handler>
            <event>
                <name>Allocate</name>
                <group>Process</group>
            </event>
            <do>allocate memory</do>
            <chains>
                <event>
                    <name>Ready</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>End</name>
                <group>Process</group>
            </event>
            <do>free memory</do>
            <chains>
                <event>
                    <name>Kill</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>Load</name>
                <group>Process</group>
            </event>
            <do>load requested pages into memory</do>
            <chains>
                <event>
                    <name>Run</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>IoOperation</name>
                <group>Process</group>
            </event>
            <do>perform expensive IO operations</do>
            <chains>
                <event>
                    <name>Schedule</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
    </entity>
</simulationDescription>

=== lups-ufpel/PampaSim/declarations/memoryManagement.xml
<?xml version="1.0" encoding="UTF-8"?>

<simulationDescription
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schemas/simulationDescription.xsd">
    <events>
        <import>declarations/processManagement.xml</import>
        <eventGroup name="Memory">
            <payloads>
                <class>
                    <fullyQualifiedClassName>org.pampasim.resources.Process</fullyQualifiedClassName>
                </class>
            </payloads>
            <event>Allocate</event>
            <event>AllocateFinished</event>
            <event>DeletePageTableEntry</event>
            <event>DeleteTlbEntry</event>
            <event>FreeProcessMemory</event>
            <event>FreeProcessMemoryFinished</event>
            <event>IoOperation</event>
            <event>PageFault</event>
            <event>PageHit</event>
            <event>ProcessReady</event>
            <event>DiskOperation</event>
            <event>DiskOperationFinished</event>
            <event>TlbNoTranslation</event>
            <event>TranslateVirtualAddress</event>
        </eventGroup>
    </events>

    <entity name="PageTable">
        <handler>
            <event>
                <name>DeletePageTableEntry</name>
                <group>Memory</group>
            </event>
            <do>delete page table entry</do>
            <chains>
                <event>
                    <name>FreeProcessMemory</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>Allocate</name>
                <group>Memory</group>
            </event>
            <do>allocate memory</do>
            <chains>
                <event>
                    <name>AllocateFinished</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>TlbNoTranslation</name>
                <group>Memory</group>
            </event>
            <do>check page table</do>
            <chains>
                <or>
                    <alt>
                        <event>
                            <name>PageHit</name>
                            <group>Memory</group>
                        </event>
                    </alt>
                    <alt>
                        <event>
                            <name>PageFault</name>
                            <group>Memory</group>
                        </event>
                    </alt>
                </or>
            </chains>
        </handler>
    </entity>
    <entity name="PhysicalMemory">
        <handler>
            <event>
                <name>FreeProcessMemory</name>
                <group>Memory</group>
            </event>
            <do>free process memory</do>
        </handler>
        <handler>
            <event>
                <name>PageHit</name>
                <group>Memory</group>
            </event>
            <do>page hit</do>
            <chains>
                <event>
                    <name>ProcessReady</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>PageFault</name>
                <group>Memory</group>
            </event>
            <do>page fault</do>
            <chains>
                <event>
                    <name>DiskOperation</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>DiskOperation</name>
                <group>Memory</group>
            </event>
            <do>time advance</do>
            <chains>
                <or>
                    <alt>
                        <event>
                            <name>DiskOperation</name>
                            <group>Memory</group>
                        </event>
                    </alt>
                    <alt>
                        <event>
                            <name>DiskOperationFinished</name>
                            <group>Memory</group>
                        </event>
                    </alt>
                </or>
            </chains>
        </handler>
        <handler>
            <event>
                <name>IoOperation</name>
                <group>Memory</group>
            </event>
            <do>start disk operation</do>
            <chains>
                <event>
                    <name>DiskOperation</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
    </entity>
    <entity name="TLB">
        <handler>
            <event>
                <name>TranslateVirtualAddress</name>
                <group>Memory</group>
            </event>
            <do>translate virtual address</do>
            <chains>
                <or>
                    <alt>
                        <event>
                            <name>PageHit</name>
                            <group>Memory</group>
                        </event>
                    </alt>
                    <alt>
                        <event>
                            <name>PageFault</name>
                            <group>Memory</group>
                        </event>
                    </alt>
                    <alt>
                        <event>
                            <name>TlbNoTranslation</name>
                            <group>Memory</group>
                        </event>
                    </alt>
                </or>
            </chains>
        </handler>
    </entity>
    <entity name="VirtualMemory">
        <handler>
            <event>
                <name>Allocate</name>
                <group>Process</group>
            </event>
            <do>allocate process</do>
            <chains>
                <event>
                    <name>Allocate</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>End</name>
                <group>Process</group>
            </event>
            <do>end process</do>
            <chains>
                <event>
                    <name>DeletePageTableEntry</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>Load</name>
                <group>Process</group>
            </event>
            <do>load requested pages into memory</do>
            <chains>
                <event>
                    <name>TranslateVirtualAddress</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>IoOperation</name>
                <group>Process</group>
            </event>
            <do>perform expensive IO operations</do>
            <chains>
                <event>
                    <name>DiskOperation</name>
                    <group>Memory</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>AllocateFinished</name>
                <group>Memory</group>
            </event>
            <do/>
            <chains>
                <event>
                    <name>Ready</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>FreeProcessMemoryFinished</name>
                <group>Memory</group>
            </event>
            <do>
            </do>
            <chains>
                <event>
                    <name>Kill</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>DiskOperationFinished</name>
                <group>Memory</group>
            </event>
            <do/>
            <chains>
                <event>
                    <name>Schedule</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
        <handler>
            <event>
                <name>Ready</name>
                <group>Process</group>
            </event>
            <do/>
            <chains>
                <event>
                    <name>Run</name>
                    <group>Process</group>
                </event>
            </chains>
        </handler>
    </entity>
</simulationDescription>
