=== lups-ufpel/PampaSim/sim/src/main/resources/org/pampasim/spec.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        targetNamespace="http://pampasim.org/"
        xmlns="http://pampasim.org/"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:events="http://pampasim.org/events"
        xmlns:process="http://pampasim.org/events/process"
        xmlns:decls="http://pampasim.org/spec/decls"
        elementFormDefault="qualified">
    <!-- these comments have semantic value! -->
    <!-- runtime rewrite begin -->
    <xs:import namespace="http://pampasim.org/spec/decls" schemaLocation="../../../../../../sim-datamodel/src/main/resources/org/pampasim/resources/specDecls.xsd"/>
    <xs:import namespace="http://pampasim.org/events" schemaLocation="../../../../../../events/src/main/resources/org/pampasim/events/event.xsd"/>
    <xs:import namespace="http://pampasim.org/events/process" schemaLocation="../../../../../../events/src/main/resources/org/pampasim/events/processCreationData.xsd"/>
    <xs:import namespace="http://pampasim.org/events/memory" schemaLocation="../../../../../../memory/src/main/resources/org/pampasim/resources/memory/memoryProcessCreationData.xsd"/>
    <xs:import namespace="http://pampasim.org/memory" schemaLocation="../../../../../../memory/src/main/resources/org/pampasim/resources/memory/MemoryManagement.xsd"/>
    <!-- runtime rewrite end -->

    <xs:element name="spec">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="version">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="major" type="xs:nonNegativeInteger"/>
                            <xs:element name="minor" type="xs:nonNegativeInteger"/>
                            <xs:element name="patch" type="xs:nonNegativeInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="extra-modules" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="module" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="entities">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="entity" minOccurs="0" maxOccurs="unbounded" type="decls:entityConfig"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="stimuli">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="event" type="events:event" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== lups-ufpel/PampaSim/sim/src/main/resources/org/pampasim/templateSpec.xml
<?xml version="1.0" encoding="UTF-8"?>

<spec
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://pampasim.org/"
        xmlns:events="http://pampasim.org/events"
        xmlns:process="http://pampasim.org/events/process"
        xmlns:decls="http://pampasim.org/spec/decls"
        xsi:schemaLocation=
                "http://pampasim.org/  /org/pampasim/spec.xsd
                 http://pampasim.org/events/ /org/pampasim/events/event.xsd
                 http://pampasim.org/events/process/ /org/pampasim/events/processCreationData.xsd
                 http://pampasim.org/spec/decls/ /org/pampasim/resources/specDecls.xsd"
        >
    <version>
        <major>0</major>
        <minor>0</minor>
        <patch>0</patch>
    </version>
    <entities>
        <entity>
            <decls:fullyQualifiedClassName>org.pampasim.entity.schedulers.FCFS</decls:fullyQualifiedClassName>
        </entity>
    </entities>
    <stimuli>
    </stimuli>
</spec>
